<?php

namespace Ramon\Backup\Database\Emitter;

use Ramon\Backup\Database\Dialect;
use Ramon\Backup\Database\Schema\Column;
use Ramon\Backup\Database\Schema\ColumnType;
use Ramon\Backup\Database\Schema\Table;

/**
 * Emitter for PostgreSQL 10+. Six notable choices, each driven by
 * what PG 10 actually permits without superuser on a managed host AND
 * by the reality that source MySQL data is rarely "clean":
 *
 *   - Foreign keys are emitted as separate `ALTER TABLE ADD CONSTRAINT
 *     ... NOT VALID` statements AFTER all data is loaded, never inline
 *     in CREATE TABLE. Three reasons: (a) PG validates parent-table
 *     existence at CREATE TABLE time, and our tables are emitted
 *     alphabetically — `discussions` would reference `users` before
 *     `users` exists. (b) Adding the constraint after data lets us
 *     load rows in any order without FK violations. (c) `NOT VALID`
 *     skips checking pre-existing rows: MySQL routinely permits
 *     orphan rows when `FOREIGN_KEY_CHECKS=0` is set during inserts,
 *     so a strict re-validation against PG would refuse to install
 *     the constraint at all and the migration would lose the FK
 *     entirely. New writes still get checked. This also sidesteps
 *     `SET session_replication_role = 'replica'`, which needs
 *     superuser and fails on RDS/Neon/Supabase.
 *
 *   - Auto-increment columns are emitted as `GENERATED BY DEFAULT AS
 *     IDENTITY` (PG 10+, SQL-standard). Inserts include explicit IDs
 *     from the source dump, and `emitPostDataFixups()` resyncs the
 *     sequence afterward so subsequent INSERTs without an explicit ID
 *     don't collide. `pg_get_serial_sequence` works for IDENTITY
 *     columns since PG 10 (docs explicitly cover this case).
 *
 *   - Index names are namespaced per-schema in PG (vs. per-table in
 *     MySQL/MariaDB). MySQL forums frequently end up with `card_id`
 *     as an index on multiple tables; emitting them verbatim collides.
 *     We prefix every non-PK index with `<table>__` when it's not
 *     already prefixed, which preserves uniqueness without inventing
 *     long synthesised names.
 *
 *   - ENUM columns are emitted as plain TEXT, NOT TEXT + CHECK. MySQL
 *     silently coerces invalid ENUM values to `''` on insert and
 *     stores them — production MySQL data routinely contains values
 *     outside the declared member list. A CHECK on the destination
 *     would reject those rows entirely (we measured 8 rows lost on a
 *     real forum due to a single dirty `product_type` column). The
 *     introspector still records the original member list as a
 *     translation note so the admin knows the constraint is gone.
 *
 *   - Indexes that would blow PG's btree row-size limit are SKIPPED.
 *     Two cases trigger this: (a) MySQL FULLTEXT/SPATIAL indexes,
 *     which have no portable PG equivalent (a real translation
 *     would mean GIN + tsvector + a separate populated column, well
 *     outside what a backup tool should be doing), and (b) plain
 *     btree indexes that include any TEXT/MEDIUMTEXT/LONGTEXT/BLOB
 *     column — MySQL silently takes a key prefix on these, while PG
 *     refuses any row whose indexed value exceeds ~2704 bytes (1/3
 *     of an 8KB page) at INSERT time. We measured this on a real
 *     forum: posts.content with a 2920-byte post lost the entire
 *     INSERT batch. Skipping the index preserves all rows; an admin
 *     who needs full-text search uses Flarum's search extension
 *     anyway, which builds its own GIN/Meilisearch indexes.
 *
 *   - All session prep is plain client setup (encoding, string
 *     conformance) — no privileged GUCs are touched.
 */
class PostgresEmitter extends AbstractEmitter
{
    /** @var list<string> Cross-engine translation notes from this emitter. */
    private array $warnings = [];

    /**
     * Notes about lossy translations the emitter applied — currently
     * just "skipped index X because PG can't support it". Surfaced
     * alongside the introspector's warnings on the export progress
     * screen so the admin sees the full picture.
     *
     * @return list<string>
     */
    public function warnings(): array
    {
        return $this->warnings;
    }

    protected function identQuote(): string
    {
        return '"';
    }

    public function targetTag(): string
    {
        return Dialect::POSTGRES->value;
    }

    public function preamble(): string
    {
        $now = gmdate('Y-m-d H:i:s');
        return implode($this->delimiter(), [
            "-- Flarum backup — database dump (target: postgres)",
            "-- Generated at $now UTC",
            "SET client_encoding = 'UTF8'",
            "SET standard_conforming_strings = on",
        ]) . $this->delimiter();
    }

    public function epilogue(): string
    {
        // No session-level toggles to undo. FK constraints have
        // already been (re-)added in emitPostDataFixups, so the
        // database is fully consistent on exit.
        return '';
    }

    public function emitSchema(Table $table): string
    {
        $name = $this->quoteIdent($table->name);

        // Foreign keys are intentionally OMITTED from CREATE TABLE here.
        // PG validates the referenced table's existence at create time,
        // and our tables come out alphabetically — the dump would
        // otherwise fail any time a child table sorts before its
        // parent. They re-appear via ALTER TABLE in emitPostDataFixups
        // after all rows are loaded.
        $lines = [];
        foreach ($table->columns as $col) {
            $lines[] = '  ' . $this->columnDdl($col);
        }
        if (! empty($table->primaryKey)) {
            $lines[] = '  PRIMARY KEY (' . $this->columnList($table->primaryKey) . ')';
        }

        $body = implode(",\n", $lines);
        $create = "CREATE TABLE $name (\n$body\n)";
        $create = preg_replace('/\s+/', ' ', $create);

        // CASCADE on DROP also tears down any FK from other tables that
        // pointed here, so a re-run starts from a clean slate.
        $sql = 'DROP TABLE IF EXISTS ' . $name . ' CASCADE' . $this->delimiter()
             . $create . $this->delimiter();

        // Indexes are separate statements in PG and live in a single
        // schema-wide namespace — MySQL allows two tables to both have
        // a `card_id` index, PG would error "relation already exists".
        // Prefix with the table name when the source name doesn't
        // already incorporate it (Laravel's default index naming
        // convention is `<table>_<col>_index`, so most names already
        // pass this check).
        //
        // Two index shapes are silently dropped here, with a warning,
        // because PG can't replicate them faithfully:
        //   - FULLTEXT / SPATIAL — no portable equivalent.
        //   - btree on TEXT/BLOB columns — MySQL stores a key prefix,
        //     PG would refuse any row > 2704 bytes (1/3 of a page).
        //     The DATA still arrives intact; only the index is gone.
        foreach ($table->indexes as $idx) {
            if ($idx->primary) continue;

            $skipReason = $this->indexSkipReason($table, $idx);
            if ($skipReason !== null) {
                $this->warnings[] = sprintf(
                    'Index `%s`.`%s` skipped on PostgreSQL: %s. The underlying data is preserved; if you rely on this index for queries, recreate it manually with a tailored expression (e.g. `md5(col)` for equality lookups, or a GIN tsvector index for full-text search).',
                    $table->name,
                    $idx->name,
                    $skipReason,
                );
                continue;
            }

            $unique  = $idx->unique ? 'UNIQUE ' : '';
            $idxName = $this->namespacedIndexName($table->name, $idx->name);
            $sql .= 'CREATE ' . $unique . 'INDEX ' . $this->quoteIdent($idxName)
                . ' ON ' . $name . ' (' . $this->columnList($idx->columns) . ')'
                . $this->delimiter();
        }
        return $sql;
    }

    /**
     * Return the human-readable reason the index can't be created on
     * PG, or `null` if it's safe to emit. Reasons:
     *   - FULLTEXT / SPATIAL: no btree-equivalent on PG.
     *   - btree over a TEXT/BLOB column: PG btree refuses rows whose
     *     indexed values exceed ~2704 bytes; MySQL silently takes a
     *     key prefix instead, so the source is fine but the
     *     destination would lose any insert that exceeds the limit.
     */
    private function indexSkipReason(Table $table, \Ramon\Backup\Database\Schema\Index $idx): ?string
    {
        $kind = strtoupper((string) ($idx->kind ?? ''));
        if ($kind === 'FULLTEXT') {
            return 'FULLTEXT indexes are MySQL-specific';
        }
        if ($kind === 'SPATIAL') {
            return 'SPATIAL indexes require PostGIS, not portable';
        }

        // The unbounded text/blob types — TEXT/MEDIUMTEXT/LONGTEXT and
        // their BLOB siblings — can hold values that exceed PG's btree
        // page-third limit (~2704 bytes). VARCHAR/CHAR are bounded by
        // their declared length and stay safe; ENUM is short by
        // construction.
        $unsafe = [
            ColumnType::TEXT, ColumnType::MEDIUMTEXT, ColumnType::LONGTEXT,
            ColumnType::BLOB, ColumnType::MEDIUMBLOB, ColumnType::LONGBLOB,
        ];
        foreach ($idx->columns as $colName) {
            $col = $table->column($colName);
            if ($col !== null && in_array($col->type, $unsafe, true)) {
                return sprintf(
                    'btree indexes over %s columns can exceed PG\'s 2704-byte index-tuple limit',
                    strtoupper($col->type->value)
                );
            }
        }
        return null;
    }

    /**
     * MySQL index names are unique per-table; Postgres index names
     * are unique per-schema. When the source name doesn't already
     * include the table prefix (as Laravel-generated names do —
     * `<table>_<col>_index`), prepend `<table>__` so multiple tables
     * sharing a short index name (`card_id`, `user_id`, …) don't
     * collide on the destination.
     */
    private function namespacedIndexName(string $table, string $idxName): string
    {
        if (str_starts_with($idxName, $table . '_')) {
            return $idxName;
        }
        return $table . '__' . $idxName;
    }

    public function emitInserts(Table $table, array $rows): string
    {
        if (empty($rows)) return '';
        $name = $this->quoteIdent($table->name);
        $columns = array_map(fn (Column $c) => $c->name, $table->columns);
        $colList = $this->columnList($columns);

        $valueGroups = [];
        foreach ($rows as $row) {
            $vals = [];
            foreach ($table->columns as $col) {
                $vals[] = $this->quoteValue($col, $row[$col->name] ?? null);
            }
            $valueGroups[] = '(' . implode(',', $vals) . ')';
        }

        return 'INSERT INTO ' . $name . ' (' . $colList . ') VALUES '
            . implode(',', $valueGroups) . $this->delimiter();
    }

    /**
     * Two distinct fixups, both safe to run only after the table's
     * data is in place:
     *
     *   1. Foreign keys — added now (rather than at CREATE TABLE) so
     *      the referenced table is guaranteed to exist and the rows
     *      we just loaded validate in one batch. ON DELETE / ON UPDATE
     *      clauses survive verbatim from the source.
     *
     *   2. Sequence resync — bulk inserts that include explicit IDs
     *      leave the IDENTITY sequence sitting at 1; a subsequent
     *      `INSERT` without an ID would then collide. `pg_get_serial_-
     *      sequence` returns the sequence backing both legacy SERIAL
     *      and PG 10+ IDENTITY columns; the COALESCE handles the case
     *      where the table has zero rows.
     */
    public function emitPostDataFixups(Table $table): string
    {
        $sql = '';
        $tbl = $this->quoteIdent($table->name);

        foreach ($table->foreignKeys as $fk) {
            $sql .= 'ALTER TABLE ' . $tbl
                . ' ADD CONSTRAINT ' . $this->quoteIdent($fk->name)
                . ' FOREIGN KEY (' . $this->columnList($fk->columns) . ')'
                . ' REFERENCES ' . $this->quoteIdent($fk->refTable)
                . ' (' . $this->columnList($fk->refColumns) . ')';
            if ($fk->onDelete) $sql .= ' ON DELETE ' . $fk->onDelete;
            if ($fk->onUpdate) $sql .= ' ON UPDATE ' . $fk->onUpdate;
            // `NOT VALID` skips the consistency check against rows
            // already present. MySQL routinely permits orphan rows
            // (any insert under `SET FOREIGN_KEY_CHECKS=0`), so the
            // pre-existing data on the source may not satisfy the FK.
            // Without `NOT VALID` the migration would lose either the
            // constraint or the orphan rows; with it, the constraint
            // installs cleanly and only NEW writes are validated.
            // Operators who want full validation can run
            // `ALTER TABLE ... VALIDATE CONSTRAINT ...` after fixing
            // the orphan rows.
            $sql .= ' NOT VALID' . $this->delimiter();
        }

        foreach ($table->autoIncrementColumns() as $col) {
            $tableLit = $this->quoteString($table->name);
            $colLit   = $this->quoteString($col);
            $c        = $this->quoteIdent($col);
            $sql .= "SELECT setval(pg_get_serial_sequence($tableLit, $colLit), "
                  . "COALESCE((SELECT MAX($c) FROM $tbl), 0) + 1, false)"
                  . $this->delimiter();
        }
        return $sql;
    }

    /** @param list<string> $columns */
    private function columnList(array $columns): string
    {
        return implode(', ', array_map(fn ($c) => $this->quoteIdent($c), $columns));
    }

    private function columnDdl(Column $col): string
    {
        $sql = $this->quoteIdent($col->name) . ' ' . $this->columnTypeSql($col);
        if ($col->autoIncrement) {
            $sql .= ' GENERATED BY DEFAULT AS IDENTITY';
        }
        $sql .= $col->nullable ? ' NULL' : ' NOT NULL';

        if (! $col->autoIncrement && ($col->default !== null || $col->defaultIsExpression)) {
            $sql .= ' DEFAULT ' . $this->renderDefault($col);
        }
        // ENUM is intentionally emitted as plain TEXT here — no CHECK.
        // MySQL silently coerces out-of-range values to `''` and
        // stores them, so production data routinely contains values
        // outside the declared enum member list. A CHECK constraint
        // on the destination would reject those rows in bulk and the
        // entire INSERT batch would fail (we measured 8 rows lost on
        // a real forum's `marketplace_order_items.product_type`
        // because of exactly this). The introspector records the
        // original member list as a translation note so the admin
        // knows the constraint isn't being recreated.
        return $sql;
    }

    private function columnTypeSql(Column $col): string
    {
        return match ($col->type) {
            ColumnType::BOOL       => 'BOOLEAN',
            ColumnType::TINYINT    => 'SMALLINT',
            ColumnType::SMALLINT   => 'SMALLINT',
            ColumnType::INTEGER    => 'INTEGER',
            ColumnType::BIGINT     => 'BIGINT',
            ColumnType::DECIMAL    => 'NUMERIC(' . ($col->precision ?? 10) . ',' . ($col->scale ?? 0) . ')',
            ColumnType::FLOAT      => 'REAL',
            ColumnType::DOUBLE     => 'DOUBLE PRECISION',
            ColumnType::CHAR       => 'CHAR(' . ($col->length ?? 1) . ')',
            ColumnType::VARCHAR    => 'VARCHAR(' . ($col->length ?? 255) . ')',
            ColumnType::TEXT,
            ColumnType::MEDIUMTEXT,
            ColumnType::LONGTEXT,
            ColumnType::ENUM       => 'TEXT',
            ColumnType::BINARY,
            ColumnType::VARBINARY,
            ColumnType::BLOB,
            ColumnType::MEDIUMBLOB,
            ColumnType::LONGBLOB   => 'BYTEA',
            ColumnType::DATE       => 'DATE',
            ColumnType::TIME       => 'TIME',
            ColumnType::DATETIME   => 'TIMESTAMP',
            ColumnType::TIMESTAMP  => 'TIMESTAMP',
            ColumnType::JSON       => 'JSONB',
            ColumnType::UUID       => 'UUID',
        };
    }

    private function renderDefault(Column $col): string
    {
        if ($col->defaultIsExpression && $col->default !== null) {
            // CURRENT_TIMESTAMP and friends pass through.
            return $col->default;
        }
        if ($col->default === null) {
            return 'NULL';
        }
        if ($col->type === ColumnType::BOOL) {
            return in_array(strtolower($col->default), ['1', 'true', 't'], true) ? 'TRUE' : 'FALSE';
        }
        if ($col->type->isInteger() || in_array($col->type, [ColumnType::FLOAT, ColumnType::DOUBLE, ColumnType::DECIMAL], true)) {
            return is_numeric($col->default) ? $col->default : '0';
        }
        return $this->quoteString($col->default);
    }

    private function quoteValue(Column $col, mixed $value): string
    {
        if ($value === null) return 'NULL';

        if ($col->type === ColumnType::BOOL) {
            if (is_bool($value)) return $value ? 'TRUE' : 'FALSE';
            if (is_numeric($value)) return ((int) $value) ? 'TRUE' : 'FALSE';
            $s = strtolower((string) $value);
            return in_array($s, ['1', 'true', 't'], true) ? 'TRUE' : 'FALSE';
        }

        if ($col->type->isInteger()) {
            if (is_bool($value)) return $value ? '1' : '0';
            return (string) (is_numeric($value) ? $value : 0);
        }

        if (in_array($col->type, [ColumnType::FLOAT, ColumnType::DOUBLE, ColumnType::DECIMAL], true)) {
            return is_numeric($value) ? (string) $value : '0';
        }

        if ($col->type->isBinary()) {
            $bytes = is_resource($value) ? (stream_get_contents($value) ?: '') : (string) $value;
            // PG bytea hex literal: '\xDEADBEEF'
            return $this->quoteString('\\x' . bin2hex($bytes));
        }

        if ($col->type === ColumnType::JSON) {
            // JSON sometimes arrives already-encoded (string) or as
            // an associative array (PG returns parsed). Either way,
            // emit a JSON-encoded string literal — JSONB column will
            // parse it back on insert.
            $s = is_string($value) ? $value : json_encode($value, JSON_UNESCAPED_UNICODE);
            return $this->quoteString((string) $s);
        }

        if (! is_string($value)) {
            $value = (string) $value;
        }
        return $this->quoteString($value);
    }
}
