<?php

namespace Ramon\Backup\Database\Emitter;

use Ramon\Backup\Database\Dialect;
use Ramon\Backup\Database\Schema\Column;
use Ramon\Backup\Database\Schema\ColumnType;
use Ramon\Backup\Database\Schema\Table;

/**
 * Emitter for PostgreSQL 10+. Three notable choices, each driven by
 * what PG 10 actually permits without superuser on a managed host:
 *
 *   - Foreign keys are emitted as separate `ALTER TABLE ADD CONSTRAINT`
 *     statements AFTER all data is loaded, never inline in CREATE
 *     TABLE. Two reasons: (a) PG validates parent-table existence at
 *     CREATE TABLE time, and our tables are emitted alphabetically —
 *     `discussions` would reference `users` before `users` exists.
 *     (b) Adding the constraint after data lets us load rows in any
 *     order without FK violations, then validate in one pass at the
 *     end. This sidesteps `SET session_replication_role = 'replica'`,
 *     which requires superuser and so fails on RDS/Neon/Supabase.
 *
 *   - Auto-increment columns are emitted as `GENERATED BY DEFAULT AS
 *     IDENTITY` (PG 10+, SQL-standard). Inserts include explicit IDs
 *     from the source dump, and `emitPostDataFixups()` resyncs the
 *     sequence afterward so subsequent INSERTs without an explicit ID
 *     don't collide. `pg_get_serial_sequence` works for IDENTITY
 *     columns since PG 10 (docs explicitly cover this case).
 *
 *   - All session prep is plain client setup (encoding, string
 *     conformance) — no privileged GUCs are touched.
 */
class PostgresEmitter extends AbstractEmitter
{
    protected function identQuote(): string
    {
        return '"';
    }

    public function targetTag(): string
    {
        return Dialect::POSTGRES->value;
    }

    public function preamble(): string
    {
        $now = gmdate('Y-m-d H:i:s');
        return implode($this->delimiter(), [
            "-- Flarum backup — database dump (target: postgres)",
            "-- Generated at $now UTC",
            "SET client_encoding = 'UTF8'",
            "SET standard_conforming_strings = on",
        ]) . $this->delimiter();
    }

    public function epilogue(): string
    {
        // No session-level toggles to undo. FK constraints have
        // already been (re-)added in emitPostDataFixups, so the
        // database is fully consistent on exit.
        return '';
    }

    public function emitSchema(Table $table): string
    {
        $name = $this->quoteIdent($table->name);

        // Foreign keys are intentionally OMITTED from CREATE TABLE here.
        // PG validates the referenced table's existence at create time,
        // and our tables come out alphabetically — the dump would
        // otherwise fail any time a child table sorts before its
        // parent. They re-appear via ALTER TABLE in emitPostDataFixups
        // after all rows are loaded.
        $lines = [];
        foreach ($table->columns as $col) {
            $lines[] = '  ' . $this->columnDdl($col);
        }
        if (! empty($table->primaryKey)) {
            $lines[] = '  PRIMARY KEY (' . $this->columnList($table->primaryKey) . ')';
        }

        $body = implode(",\n", $lines);
        $create = "CREATE TABLE $name (\n$body\n)";
        $create = preg_replace('/\s+/', ' ', $create);

        // CASCADE on DROP also tears down any FK from other tables that
        // pointed here, so a re-run starts from a clean slate.
        $sql = 'DROP TABLE IF EXISTS ' . $name . ' CASCADE' . $this->delimiter()
             . $create . $this->delimiter();

        // Indexes are separate statements in PG.
        foreach ($table->indexes as $idx) {
            if ($idx->primary) continue;
            $unique = $idx->unique ? 'UNIQUE ' : '';
            $sql .= 'CREATE ' . $unique . 'INDEX ' . $this->quoteIdent($idx->name)
                . ' ON ' . $name . ' (' . $this->columnList($idx->columns) . ')'
                . $this->delimiter();
        }
        return $sql;
    }

    public function emitInserts(Table $table, array $rows): string
    {
        if (empty($rows)) return '';
        $name = $this->quoteIdent($table->name);
        $columns = array_map(fn (Column $c) => $c->name, $table->columns);
        $colList = $this->columnList($columns);

        $valueGroups = [];
        foreach ($rows as $row) {
            $vals = [];
            foreach ($table->columns as $col) {
                $vals[] = $this->quoteValue($col, $row[$col->name] ?? null);
            }
            $valueGroups[] = '(' . implode(',', $vals) . ')';
        }

        return 'INSERT INTO ' . $name . ' (' . $colList . ') VALUES '
            . implode(',', $valueGroups) . $this->delimiter();
    }

    /**
     * Two distinct fixups, both safe to run only after the table's
     * data is in place:
     *
     *   1. Foreign keys — added now (rather than at CREATE TABLE) so
     *      the referenced table is guaranteed to exist and the rows
     *      we just loaded validate in one batch. ON DELETE / ON UPDATE
     *      clauses survive verbatim from the source.
     *
     *   2. Sequence resync — bulk inserts that include explicit IDs
     *      leave the IDENTITY sequence sitting at 1; a subsequent
     *      `INSERT` without an ID would then collide. `pg_get_serial_-
     *      sequence` returns the sequence backing both legacy SERIAL
     *      and PG 10+ IDENTITY columns; the COALESCE handles the case
     *      where the table has zero rows.
     */
    public function emitPostDataFixups(Table $table): string
    {
        $sql = '';
        $tbl = $this->quoteIdent($table->name);

        foreach ($table->foreignKeys as $fk) {
            $sql .= 'ALTER TABLE ' . $tbl
                . ' ADD CONSTRAINT ' . $this->quoteIdent($fk->name)
                . ' FOREIGN KEY (' . $this->columnList($fk->columns) . ')'
                . ' REFERENCES ' . $this->quoteIdent($fk->refTable)
                . ' (' . $this->columnList($fk->refColumns) . ')';
            if ($fk->onDelete) $sql .= ' ON DELETE ' . $fk->onDelete;
            if ($fk->onUpdate) $sql .= ' ON UPDATE ' . $fk->onUpdate;
            $sql .= $this->delimiter();
        }

        foreach ($table->autoIncrementColumns() as $col) {
            $tableLit = $this->quoteString($table->name);
            $colLit   = $this->quoteString($col);
            $c        = $this->quoteIdent($col);
            $sql .= "SELECT setval(pg_get_serial_sequence($tableLit, $colLit), "
                  . "COALESCE((SELECT MAX($c) FROM $tbl), 0) + 1, false)"
                  . $this->delimiter();
        }
        return $sql;
    }

    /** @param list<string> $columns */
    private function columnList(array $columns): string
    {
        return implode(', ', array_map(fn ($c) => $this->quoteIdent($c), $columns));
    }

    private function columnDdl(Column $col): string
    {
        $sql = $this->quoteIdent($col->name) . ' ' . $this->columnTypeSql($col);
        if ($col->autoIncrement) {
            $sql .= ' GENERATED BY DEFAULT AS IDENTITY';
        }
        $sql .= $col->nullable ? ' NULL' : ' NOT NULL';

        if (! $col->autoIncrement && ($col->default !== null || $col->defaultIsExpression)) {
            $sql .= ' DEFAULT ' . $this->renderDefault($col);
        }
        if ($col->type === ColumnType::ENUM && ! empty($col->enumValues)) {
            $list = implode(',', array_map(fn ($v) => $this->quoteString((string) $v), $col->enumValues));
            $sql .= ' CHECK (' . $this->quoteIdent($col->name) . ' IN (' . $list . '))';
        }
        return $sql;
    }

    private function columnTypeSql(Column $col): string
    {
        return match ($col->type) {
            ColumnType::BOOL       => 'BOOLEAN',
            ColumnType::TINYINT    => 'SMALLINT',
            ColumnType::SMALLINT   => 'SMALLINT',
            ColumnType::INTEGER    => 'INTEGER',
            ColumnType::BIGINT     => 'BIGINT',
            ColumnType::DECIMAL    => 'NUMERIC(' . ($col->precision ?? 10) . ',' . ($col->scale ?? 0) . ')',
            ColumnType::FLOAT      => 'REAL',
            ColumnType::DOUBLE     => 'DOUBLE PRECISION',
            ColumnType::CHAR       => 'CHAR(' . ($col->length ?? 1) . ')',
            ColumnType::VARCHAR    => 'VARCHAR(' . ($col->length ?? 255) . ')',
            ColumnType::TEXT,
            ColumnType::MEDIUMTEXT,
            ColumnType::LONGTEXT,
            ColumnType::ENUM       => 'TEXT',
            ColumnType::BINARY,
            ColumnType::VARBINARY,
            ColumnType::BLOB,
            ColumnType::MEDIUMBLOB,
            ColumnType::LONGBLOB   => 'BYTEA',
            ColumnType::DATE       => 'DATE',
            ColumnType::TIME       => 'TIME',
            ColumnType::DATETIME   => 'TIMESTAMP',
            ColumnType::TIMESTAMP  => 'TIMESTAMP',
            ColumnType::JSON       => 'JSONB',
            ColumnType::UUID       => 'UUID',
        };
    }

    private function renderDefault(Column $col): string
    {
        if ($col->defaultIsExpression && $col->default !== null) {
            // CURRENT_TIMESTAMP and friends pass through.
            return $col->default;
        }
        if ($col->default === null) {
            return 'NULL';
        }
        if ($col->type === ColumnType::BOOL) {
            return in_array(strtolower($col->default), ['1', 'true', 't'], true) ? 'TRUE' : 'FALSE';
        }
        if ($col->type->isInteger() || in_array($col->type, [ColumnType::FLOAT, ColumnType::DOUBLE, ColumnType::DECIMAL], true)) {
            return is_numeric($col->default) ? $col->default : '0';
        }
        return $this->quoteString($col->default);
    }

    private function quoteValue(Column $col, mixed $value): string
    {
        if ($value === null) return 'NULL';

        if ($col->type === ColumnType::BOOL) {
            if (is_bool($value)) return $value ? 'TRUE' : 'FALSE';
            if (is_numeric($value)) return ((int) $value) ? 'TRUE' : 'FALSE';
            $s = strtolower((string) $value);
            return in_array($s, ['1', 'true', 't'], true) ? 'TRUE' : 'FALSE';
        }

        if ($col->type->isInteger()) {
            if (is_bool($value)) return $value ? '1' : '0';
            return (string) (is_numeric($value) ? $value : 0);
        }

        if (in_array($col->type, [ColumnType::FLOAT, ColumnType::DOUBLE, ColumnType::DECIMAL], true)) {
            return is_numeric($value) ? (string) $value : '0';
        }

        if ($col->type->isBinary()) {
            $bytes = is_resource($value) ? (stream_get_contents($value) ?: '') : (string) $value;
            // PG bytea hex literal: '\xDEADBEEF'
            return $this->quoteString('\\x' . bin2hex($bytes));
        }

        if ($col->type === ColumnType::JSON) {
            // JSON sometimes arrives already-encoded (string) or as
            // an associative array (PG returns parsed). Either way,
            // emit a JSON-encoded string literal — JSONB column will
            // parse it back on insert.
            $s = is_string($value) ? $value : json_encode($value, JSON_UNESCAPED_UNICODE);
            return $this->quoteString((string) $s);
        }

        if (! is_string($value)) {
            $value = (string) $value;
        }
        return $this->quoteString($value);
    }
}
